In [2]:
import numpy as np

In [9]:
a = np.array([[1, 1, 1], [2, 2, 2]])
b = np.arange(0, 3).reshape((3, 1))

a, b

(array([[1, 1, 1],
        [2, 2, 2]]),
 array([[0],
        [1],
        [2]]))

In [10]:
np.dot(a, b)

array([[3],
       [6]])

In [11]:
bool(None)

False

# Row vector multiplied by column vector = matrix
(x, 1) * (1, x) => (x, x) dimensions
Backprop "# compute delta values for the output layer with delta = dC/da * sigmoid-prime(z)"

In [36]:
x = 3
a = np.random.randn(x, 1)
b = np.random.randn(1, x)

a, b

np.matmul(a, b)


array([[-0.10308143,  0.1432308 , -0.0047769 ],
       [ 1.10552012, -1.53611114,  0.05123099],
       [-0.63081188,  0.87650793, -0.0292325 ]])

In [40]:
c = np.matmul(a, b)
np.matmul(c, a) == np.dot(c, a)

array([[ True],
       [ True],
       [ True]])